from django.db import models

class Vote(models.Model):
  number = models.IntegerField()
  date = models.DateField()
  time = models.TimeField()
  motion_ch = models.CharField(max_length=200)
  motion_en = models.CharField(max_length=100)
  mover_ch = models.CharField(max_length=10)
  mover_en = models.CharField(max_length=100)
  mover_type = models.CharField(max_length=50)
  separate_mechanism = models.CharField(max_length=3)
  fc_present = models.IntegerField(null=True,blank=True)
  fc_vote = models.IntegerField(null=True,blank=True)
  fc_yes = models.IntegerField(null=True,blank=True)
  fc_no = models.IntegerField(null=True,blank=True)
  fc_abstain = models.IntegerField(null=True,blank=True)
  fc_result = models.CharField(max_length=10,null=True,blank=True)
  gc_present = models.IntegerField(null=True,blank=True)
  gc_vote = models.IntegerField(null=True,blank=True)
  gc_yes = models.IntegerField(null=True,blank=True)
  gc_no = models.IntegerField(null=True,blank=True)
  gc_abstain = models.IntegerField(null=True,blank=True)
  gc_result = models.CharField(max_length=10,null=True,blank=True)
  present = models.IntegerField(null=True,blank=True)
  vote = models.IntegerField(null=True,blank=True)
  yes = models.IntegerField(null=True,blank=True)
  no = models.IntegerField(null=True,blank=True)
  abstain = models.IntegerField(null=True,blank=True)
  result = models.CharField(max_length=10)

class IndividualVote(models.Model):
  number = models.IntegerField()
  date = models.DateField()
  name_ch = models.CharField(max_length=10)
  name_en = models.CharField(max_length=100)
  constituency = models.CharField(max_length=15)
  vote = models.CharField(max_length=10)

