import scrapy 

class VoteItem(scrapy.Item):
    number = scrapy.Field()
    date = scrapy.Field()
    time = scrapy.Field()
    motion_ch = scrapy.Field()
    motion_en = scrapy.Field()
    mover_ch = scrapy.Field()
    mover_en = scrapy.Field()
    mover_type = scrapy.Field()
    separate_mechanism = scrapy.Field()
    fc_present = scrapy.Field()
    fc_vote = scrapy.Field()
    fc_yes = scrapy.Field()
    fc_no = scrapy.Field()
    fc_abstain = scrapy.Field()
    fc_result = scrapy.Field()
    gc_present = scrapy.Field()
    gc_vote = scrapy.Field()
    gc_yes = scrapy.Field()
    gc_no = scrapy.Field()
    gc_abstain = scrapy.Field()
    gc_result = scrapy.Field()
    present = scrapy.Field()
    vote = scrapy.Field()
    yes = scrapy.Field()
    no = scrapy.Field()
    abstain = scrapy.Field()
    result = scrapy.Field()


class IndividualVoteItem(scrapy.Item):
    number = scrapy.Field()
    date = scrapy.Field()
    name_ch = scrapy.Field()
    name_en = scrapy.Field()
    constituency = scrapy.Field()
    vote = scrapy.Field()
